[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::pytest.PytestUnraisableExceptionWarning
env =
    D:DATABASE_PORT=5433
    D:DATABASE_NAME=shopping_db_test
    D:POSTGRES_DB=shopping_db_test
    D:SECRET_KEY=TEST_SECRET_KEY_FOR_SNAPSHOTS
    D:DATABASE_HOSTNAME=localhost