"""empty message

Revision ID: e8811b47ea20
Revises: 4543de0307f0
Create Date: 2026-04-11 05:54:39.327977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8811b47ea20'
down_revision: Union[str, None] = '4543de0307f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the custom PostgreSQL enum type first
    # KNOWLEDGE ANCHOR: PostgreSQL doesn't automatically create ENUM types.
    # We must manually create the 'userrole' type using sa.Enum(...).create()
    # before we can add the 'role' column to the 'users' table.
    user_role = sa.Enum('customer', 'seller', 'admin', name='userrole')
    user_role.create(op.get_bind())

    op.add_column('users', sa.Column('role', sa.Enum('customer', 'seller', 'admin', name='userrole'), server_default='customer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')

    # Drop the custom PostgreSQL enum type
    user_role = sa.Enum('customer', 'seller', 'admin', name='userrole')
    user_role.drop(op.get_bind())
    # ### end Alembic commands ###
